# Config file for automatic testing at travis-ci.org

language: python

python:
    - 2.7


before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda3-3.5.5-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda3/bin:$PATH
    - conda config --add channels https://conda.binstar.org/dan_blanchard
    - conda update --yes conda
  # add for profile
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq

install:
    - conda install --yes pip python=$TRAVIS_PYTHON_VERSION numpy scipy wx  h5py matplotlib dateutil sqlalchemy wxutils wxmplot nose 
    - python setup.py install
# add for profile
    - sudo apt-get install -qq g++-4.8
    - export CXX="g++-4.8"
    - pip install nose-cprof
    - pip install properform


script:
    - cd tests
    - nosetests --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_xraylarch_aaebce857b_3
    - python -m properform Push 47.88.50.110:15554 asdf_xraylarch_aaebce857b_3 ./profile_xraylarch_aaebce857b_3

 #2017-08-13 01:11:59 modified at 0 #2017-08-13 01:12:04 modified at 1 #2017-08-13 01:12:08 modified at 2 #2017-08-13 01:12:12 modified at 3